import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-main-menu',
    templateUrl: './main-menu.page.html',
    styleUrls: ['./main-menu.page.scss'],
    standalone: false
})
export class MainMenuPage implements OnInit {
    constructor(private router: Router) {}

    ngOnInit() {}

    back() {
        this.router.navigate(['/home']);
    }

    loginButton(){
        this.router.navigate(['login']);
    }
    
    page1(){
        this.router.navigate(['acc-create-pvt']);
    }
    page2(){
        this.router.navigate(['acc-create-busines']);
    }
    page3(){
        this.router.navigate(['account-prof-pvt']);
    }
    page4(){
        this.router.navigate(['account-prof-busines']);
    }
    page5(){
        this.router.navigate(['home-page']);
    }
    page6(){
        this.router.navigate(['main-menu']);
    }
    page7(){
        this.router.navigate(['terms']);
    }
    page8(){
        this.router.navigate(['login']);
    }
    page9(){
        this.router.navigate(['wallet-bundles']);
    }
    page10(){
        this.router.navigate(['my-car-ads']);
    }
    page11(){
        this.router.navigate(['your-business']);
    }
    page12(){
        this.router.navigate(['car-home']);
    }
    page13(){
        this.router.navigate(['for-sale']);
    }

    page14(){
        this.router.navigate(['sale-filters']);
    }

    page15(){
        this.router.navigate(['select-city']);
    }
    page16(){
        this.router.navigate(['registration-city']);
    }
    page17(){
        this.router.navigate(['select-car']);
    }
    page18(){
        this.router.navigate(['for-hire']);
    }
    page19(){
        this.router.navigate(['hire-filters']);
    }
    page20(){
        this.router.navigate(['Sale-single-view']);
    }
    page21(){
        this.router.navigate(['hire-single-view']);
    }
    page22(){
        this.router.navigate(['my-added-cars']);
    }
    page23(){
        this.router.navigate(['added-cars-single']);
    }
    page24(){
        this.router.navigate(['edit-reminder']);
    }
    page25(){
        this.router.navigate(['saved-ads']);
    }
    page26(){
        this.router.navigate(['listing-insurance']);
    }
    page27(){
        this.router.navigate(['listing-insurance-filter']);
    }
    page28(){
        this.router.navigate(['insurance-single-view']);
    }
    page29(){
        this.router.navigate(['listing-showroom']);
    }
    page30(){
        this.router.navigate(['listing-showroom-filter']);
    }
    page31(){
        this.router.navigate(['listing-exporter']);
    }
    page32(){
        this.router.navigate(['listing-exporter-filter']);
    }
    page33(){
        this.router.navigate(['showroom-single-view']);
    }
    page34(){
        this.router.navigate(['exporter-single-view']);
    }
    page35(){
        this.router.navigate(['listing-workshop']);
    }
    page36(){
        this.router.navigate(['listing-workshop-filter']);
    }
    page37(){
        this.router.navigate(['workshop-single-view']);
    }
    page38(){
        this.router.navigate(['listing-dealer']);
    }
    page39(){
        this.router.navigate(['listing-dealer-filter']);
    }
    page40(){
        this.router.navigate(['dealer-single-view']);
    }
    page41(){
        this.router.navigate(['listing-leasing']);
    }
    page42(){
        this.router.navigate(['listing-leasing-filter']);
    }
    page43(){
        this.router.navigate(['leasing-single-view']);
    }
    page44(){
        this.router.navigate(['listing-importer']);
    }
    page45(){
        this.router.navigate(['listing-importer-filter']);
    }
    page46(){
        this.router.navigate(['importer-single-view']);
    }
    page47(){
        this.router.navigate(['listing-drv-school']);
    }
    page48(){
        this.router.navigate(['listing-drv-school-filter']);
    }
    page49(){
        this.router.navigate(['drv-school-single-view']);
    }
    page50(){
        this.router.navigate(['ads-upgrade-hotspot']);
    }
    page51(){
        this.router.navigate(['ads-upgrade-supreme']);
    }
    page52(){
        this.router.navigate(['profile-upgrade-hotspot']);
    }
    page53(){
        this.router.navigate(['profile-upgrade-supreme']);
    }
    page54(){
        this.router.navigate(['car-sale']);
    }
    page55(){
        this.router.navigate(['car-sale-post']);
    }
    page56(){
        this.router.navigate(['car-hire']);
    }
    page57(){
        this.router.navigate(['contact-us']);
    }
    page58(){
        this.router.navigate(['advertisement']);
    }
    page59(){
        this.router.navigate(['add-your-car']);
    }
    page60(){
        this.router.navigate(['add-reminder']);
    }
    page61(){
        this.router.navigate(['sign-in']);
    }
    page62(){
        this.router.navigate(['post-dealer-busines']);
    }
    page63(){
        this.router.navigate(['post-driving-school']);
    }
    page64(){
        this.router.navigate(['post-exporter-busines']);
    }
    page65(){
        this.router.navigate(['post-importer-busines']);
    }
    page66(){
        this.router.navigate(['post-insurance-busines']);
    }
    page67(){
        this.router.navigate(['post-leasing-busines']);
    }
    page68(){
        this.router.navigate(['post-showroom-busines']);
    }
    page69(){
        this.router.navigate(['post-workshop-busines']);
    }

}
